
name: Build Linux and Windows Java OSGi bundles for use in Dawn

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      max-parallel: 2
      matrix:
        include:
          - ARCH: x86_64
            OS: ubuntu-24.04
            PLAT: "2014"
          - ARCH: aarch64
            OS: ubuntu-24.04-arm
            PLAT: "2014"

    # The type of runner that the job will run on
    runs-on: ${{ matrix.OS }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Use docker image of Centos 6 or 7 with some devel packages as defined in PEP571 and PEP599
      - name: Make Linux and Windows bindings (${{ matrix.ARCH }})
        run: |
          docker run --rm --env="PLAT=${{ matrix.PLAT }}" --env="ARCH=${{ matrix.ARCH }}" --volume $(pwd):/io ghcr.io/diamondlightsource/manylinux-dls-${{ matrix.PLAT }}_${{ matrix.ARCH }}:latest /bin/bash /io/releng/build_linux_bindings.sh

      - uses: actions/upload-artifact@v4
        with:
          name: cbflib-build-linux-${{ matrix.ARCH }}
          path: dist

